### PR TITLE
Fix resize crash

### PR DESCRIPTION
**Pull request by jscheel**
The standard buttons were being added to the web view, but they expected their superview to respond properly to resizing, and the web view didn't respond the way they expected. I have no idea what I'm doing, but this works.

### CODE REVIEW

**Comment by keiohtani** [comment]
It worked for me after adding the fix for the build. Thank you! I'd create a branch off of my branch and create a new PR for the media key fix.

**Comment by steve228uk** [comment]
This looks good to me. I'll double check this one though. Thanks for all your contributions @jscheel!

**Review by unbeatable-101 — APPROVED** [review]

**Comment by TimOliver** [comment]
I just double-checked this still works as well. This works way better than the solution I came up with independently. Nicely done!

**Comment by unbeatable-101** [comment]
@TimOliver , will we be getting a new release soon? It has been 2 years since the last one and there  have been a few merged pull requests

**Comment by TimOliver** [comment]
@unbeatable-101 I hadn't considered that far yet. 

If @steve228uk is okay with me releasing builds with my own developer certificate, I could certainly look at doing that.

**Comment by jscheel** [comment]
@TimOliver I don't have a dev account, but I'm thinking we could set up github actions to run builds automatically

**Comment by TimOliver** [comment]
@jscheel Oh yeah. I'm definitely down for automating a release pipeline. But if we don't sign them with a developer certificate (And get them notarised as well? Did I hear that's mandatory now?), macOS will refuse to open them by default.

There's certainly a lot to discuss here. It might be better to move this discussion to a new issue. :)

**Pull request merged**
