### PR TITLE
Fix mediacontrollers (next / previous)

### PR DESCRIPTION
**Pull request by FrankHeijden**
Small fix for the mediacontrollers, these "Commands" need to be enabled before they will work.

### CODE REVIEW

**Comment by quentinlasco** [comment]
Please fix it ! We love the app ♥️

**Comment by dinukapj** [comment]
@steve228uk check this out and approve, please 🙏

**Comment by el-angel** [comment]
Can this please be merged? :)

**Comment by jamieleshaw** [comment]
Please :)

**Comment by weyderfs** [comment]
I guess that this project was abandoned....

**Comment by steve228uk** [comment]
Thanks for this and sorry for the delay. Merged!

**Pull request merged**
