### PR TITLE
fix the media key issue

### PR DESCRIPTION
**Pull request by keiohtani**

### CODE REVIEW

**Comment by jelofsson** [comment]
This works for me! Thank you! 😃

**Comment by keiohtani** [comment]
@jelofsson Cool! I am glad that I was able to help!

**Comment by macx** [comment]
@keiohtani Do you have a compiled version? Please re-release this on your GitHub-Account, this one here will never be reactivated I think.

**Comment by igorrudyk** [comment]
Shall we merge it into master branch?

**Comment by MrEmelianenko** [comment]
@steve228uk may we merge it and release a new version?

**Comment by steve228uk** [comment]
@keiohtani Thanks for submitting the PR! Unfortunately while this may work due to the use of MediaKeyTap I'm not sure it's the right solution. We've been using the official MPNotificationCenter which I feel should continue to be used with a fix found.

**Comment by midN** [comment]
@keiohtani Can you please build and package release from your branch?

**Comment by keiohtani** [comment]
As @steve228uk mentioned, unfortunately, there was some issue with my solution to this problem. I will continue to work on finding the solution, but for now, this approach does not work.

**Comment by wonsuc** [comment]
@keiohtani Did you find another solution? This app will be perfect with the media key feature.

**Comment by charliebobgordon** [comment]
Has there been any progress on this yet, this is my main gripe with YouTube Music. Many thanks!

**Comment by keiohtani** [comment]
@wonsuc I did not find a solution yet. Yep, I agree. I will spend some spare time to work on this.

**Comment by ZeusFSX** [comment]
when will be merged with master?

**Comment by TotallWAR** [comment]
@keiohtani Haven't you still found solution?) This bug has been existin so long...((

**Comment by keiohtani** [comment]
> @keiohtani Haven't you still found solution?) This bug has been existin so long...((

I have not been able to work on the project lately... I will try to find some spare time to work on it.

**Comment by wonsuc** [comment]
It seems this one works with system media keys. Can you reference the source code and implement it with this app? I wish I can help but since I'm an android developer I just need to wait...

**Comment by keiohtani** [comment]
Sorry guys! I have been busy wrapping up school and finding a job. I struggled but found a job, and I got some time to work on the issue. 

The media key issue is fixed, although it may cause some issues as the author mentioned (It works just fine on my computer though! ). Since the author may not approve the change, I also publish the new version on my fork. In your own risk, you can download it from my repo. 

https://github.com/keiohtani/YouTube-Music/releases/tag/1.0.7

**Comment by wonsuc** [comment]
@keiohtani You are genius! I wanna donate for your effort.

**Comment by wonsuc** [comment]
@keiohtani Ok I found some issue.

1. I need to press Command + Enter to search songs.
2. Resize the window or full screen won't work.

I will figure out if it is a temporary issue, or it will happen continuously.

**Comment by keiohtani** [comment]
> @keiohtani Ok I found some issue.
> 
> 1. I need to press Command + Enter to search songs.
> 2. Resize the window or full screen won't work.
> 
> I will figure out if it is a temporary issue, or it will happen continuously.

Oh no, I will take a look.

**Comment by wonsuc** [comment]
> > @keiohtani Ok I found some issue.
> > 
> > 1. I need to press Command + Enter to search songs.
> > 2. Resize the window or full screen won't work.
> > 
> > I will figure out if it is a temporary issue, or it will happen continuously.
> 
> Oh no, I will take a look.

Any updates yet?

**Comment by dinukapj** [comment]
@keiohtani Your patch works but the app crashes when you resize the window. Try resizing the window from the edge and the app will crash

**Comment by jscheel** [comment]
@dinukapj @keiohtani the crash appears to be caused by moving the close/min/zoom buttons to the subview in the ViewController

**Comment by jscheel** [comment]
@dinukapj @keiohtani here's a fix for the crash on resize: https://github.com/steve228uk/YouTube-Music/pull/87

**Comment by keiohtani** [comment]
> @dinukapj @keiohtani here's a fix for the crash on resize: #87

The build was failing in my setup, but with my build fix in my PR, it works for me! Thank you!

**Review by unbeatable-101 — APPROVED** [review]

**Review by chosa91 — APPROVED** [review]

**Comment by unbeatable-101** [comment]
#81 was merged, seems to do the same thing

**Comment by droidpl** [comment]
Seems this still doesn't work for rewind/forward despite the fix in #81

**Comment by unbeatable-101** [comment]
Are you downloading from releases or building your self? The releases haven't been updated in a while.

**Comment by droidpl** [comment]
oh thought it was in the releases already 🤦  @unbeatable-101 Do you know if there is any release somewhere with the fix that I could download? Otherwise I can try to build it from code (haven't seen a guide to do so on the repo)

**Comment by unbeatable-101** [comment]
> oh thought it was in the releases already 🤦 @unbeatable-101 Do you know if there is any release somewhere with the fix that I could download? Otherwise I can try to build it from code (haven't seen a guide to do so on the repo)

I don't know of any, the last release was in 2018. I tried building it myself, but couldn't get the app to open. If you are able to do it could you tell me how?

**Comment by unbeatable-101** [comment]
> Hey folks. If you can't build your own local copy, I tried very briefly building a developer edition here.
> 
> This is by no means a production ready version (I'm still sorting out all the steps to make that happen), but if the latest release in the repo isn't cutting it for you, this might be a good stopgap for now.
> 
> Since it's not notarised, you might have to right-click it and choose "Open" the first time you launch it.
> 
> I'll keep working on updating the repo with a release that is properly notarised for production.
> 
> [YT Music.app.zip](https://github.com/steve228uk/YouTube-Music/files/5771456/YT.Music.app.zip)

Screen Shot 2021-01-05 at 12 01 50 PM

@TimOliver Sadly the file won't open, but I'm fine with the current release for now.

**Comment by unbeatable-101** [comment]
https://github.com/keiohtani/YouTube-Music/releases

In the meantime, this fork works.

**Comment by TimOliver** [comment]
@unbeatable-101 Oh dear. That's a new error I haven't seen before. Are you on Apple Silicon?

Okay. If there's a stopgap solution available now, that's good. I'll keep working on the proper release pipeline then. I'll have to make sure it has proper Apple Silicon support too.

**Comment by unbeatable-101** [comment]
@TimOliver I am

**Comment by TimOliver** [comment]
@unbeatable-101 Ahh okay. I'm still on Catalina (Big Sur has some GPU driver issues that break my monitor, so I'm waiting for Apple to fix it), so I can't build Apple Silicon builds locally yet. But if we set up a release pipeline here, we can automate building both architectures.

Thanks for the crash logs! I'll take a look in case there's anything else I missed!

**Comment by droidpl** [comment]
Do you have some README out there to build it? If so I am happy to create some GitHub actions pipeline 👍

**Comment by TimOliver** [comment]
Okay, so it's been literally over 2 years since this PR was up, but I just merged it into the app and cut a new release with it. 

While I definitely agree that the official APIs would be better, getting them to work properly in Catalina and Big Sur might take some more research (I think the `WKWebView` player itself is interfering), and so this is a viable solution in the interim.

Thanks so much for that @keiohtani!

**Comment by albertbronsky** [comment]
> Okay, so it's been literally over 2 years since this PR was up, but I just merged it into the app and cut a new release with it.
> 
> While I definitely agree that the official APIs would be better, getting them to work properly in Catalina and Big Sur might take some more research (I think the `WKWebView` player itself is interfering), and so this is a viable solution in the interim.
> 
> Thanks so much for that @keiohtani!

Finally, can confirm that Media keys are working now on macOS Big Sur 11.3.

**Comment by kadirozgunn** [comment]
Hi, I use BigSur 11.3.1 and play/stop key is works however skip buttons are not working on 11.3.1. Thank you for your effort.

**Comment by unbeatable-101** [comment]
Do they work when you have the app focused?

**Comment by unbeatable-101** [comment]
If so, see #134

**Comment by johnathanz** [comment]
I'm on Mojave (10.14.6), and like @kadirozgunn, only `play / pause` works. Skip buttons not working on latest YT Music (1.0.6).

Even if the YT Music app is in focus, skip buttons don't work.

**Pull request closed without merging**
