### PR TITLE
Block service worker from loading, (see #163)

### PR DESCRIPTION
**Pull request by jscheel**
The YouTube Music service worker's prefetch and cache seems to be breaking. This PR disables the service worker so that the requests to pull the js reach the server, instead of a broken service worker. For this to work, it requires a min version bump to 10.13. See discussion on #163

### CODE REVIEW

**Comment by TimOliver** [comment]
Thanks @jscheel! Yeah, I think at this point, fixing this issue outweighs the need for backwards support, so I think bumping to 10.13 is fine. I'll prepare a new release ASAP!

**Comment by buschtoens** [comment]
I just saw this linked in the update notes and wanted to thank you @jscheel for fixing this bug. Thanks for making my daily life a bit better! ✨

**Comment by jscheel** [comment]
You're welcome @buschtoens, I hope it works for you! There's another PR in the works (#167) that may be needed as well.

**Comment by TimOliver** [comment]
Thanks so much for the new PR @jscheel! 

I just merged it and cut a new release. It should already be live to update, so please give it a try and let me know how it goes for you! Thanks again!

**Pull request merged**
