### PR TITLE
Adds Preferences Window for Managing Shortcuts

### PR DESCRIPTION
**Pull request by ravero**
With this PR I've tried to manage the only thing that bothered me in the app, the Global Keyboard shortcuts (more specifically the Play/Pause using the Cmd+Shift+Spacebar) that was conflicting with other program that I was using this shortcut to (1Password 8).

In order to collaborate and not break existing functionality that others may be used and interested, I've implemented a preferences window that allow enabling/disabling those shortcuts. This should at least avoid the hotkeys conflict. A further improvement on this implementation would be to allow custom Shortcuts altogether, but I've found that it would require more effort than I currently would put on this.

I hope this addition helps to enhance the value of the app which for me, as a YouTube Music user, is a must on macOS.

### CODE REVIEW

**Comment by TimOliver** [comment]
Thanks for the PR @ravero! Sorry for the delay.

I'm kind of on the fence about this PR. It's kind of a workaround for the original problem with the media keys, which is also a workaround for the fact we can't directly hook the audio session in the `WKWebView` process.

I'll merge it in so we can fix the problem now, but I'm hoping to continue to find a way to hook the audio session in order to make all of these workarounds unnecessary.

**Comment by ravero** [comment]
Hey @TimOliver!
Thanks for the response. Actually the media keys is working pretty fine here without any changes. Take a look:
Screen Shot 2022-08-20 at 22 51 37

Play/Pause, Forward and Rewind are working properly from the keyboard. Don't if something has changed operating system-wise since you've started this project. This is running on latest Monterey version.

The idea of adding this Preferences screen was to at least give the user the option to at least disable or enable. I didn't had the time for a more complete experience that I originally though, that was to allow customizing the key combination completely. If you find it to be useful let me know and I'll take look when I have some time.

**Comment by michaelwills** [comment]
Great work on YT-Music @TimOliver! I happen to use the Hook app with Command+Shift+Space so every time I hook an item, the music toggles :D. I am also on Monterey and the actual media keys work in addition to your hotkey as @ravero noted.

If not, I'll try giving a build a go. I do wonder if it's the same for Ventura.

**Comment by semaperepelitsa** [comment]
@TimOliver, can you please make a release with this feature?

**Pull request merged**
